name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "v18.16.1"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os: [macos-latest, ubuntu-latest, windows-2019]
        include:
          - arch: x64
            os: macos-latest
          - arch: x64
            os: windows-2019
          - arch: x64
            os: ubuntu-latest

          - arch: x86
            os: windows-2019
          - arch: x86
            os: ubuntu-latest

          - arch: armv7
            os: ubuntu-latest
          - arch: arm64
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      TARGET_ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - name: Download source code
        shell: bash
        run: ./scripts/download.sh
      - name: Build
        shell: bash
        run: ./scripts/build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: libnode-${{ env.NODE_VERSION }}-${{ runner.os }}-${{ matrix.arch }}
          path: ./artifacts
